server {
    listen 80;
    server_name staff.nssb-maximum.ru;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name staff.nssb-maximum.ru;

    ssl_certificate /etc/letsencrypt/live/nssb-maximum.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nssb-maximum.ru/privkey.pem;

    location / {
        proxy_pass http://localhost:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
